---
# pfSense inventory for pfsensible.core playbooks
all:
  children:
    pfsense:
      hosts:
        pfsense-fw:
          ansible_host: 192.168.0.101
          ansible_user: admin
          ansible_password: unix
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/local/bin/python3.11
